services:
  description-generator:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: description-generator:latest
    ports:
      - "3003:3003"
    restart: always
    container_name: description-generator
